version: '3.8'

services:
    traefik:
        command:
          - "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedByDefault=false"
          - "--providers.docker.swarmMode=true"
          - "--providers.file.directory=/config"
          - "--providers.file.watch=true"
          - "--entrypoints.http.address=:80"
          - "--entrypoints.http.http.redirections.entryPoint.to=https"
          - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
          - "--entrypoints.https.address=:443"
          - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
          - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
          - "--certificatesresolvers.letsencrypt.acme.email=postmaster@${DOMAIN:?err}"
          - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
        image: traefik:v2.11.9
        user: "root"
        restart: always
        ports:
          - ${TRAEFIK_HTTP_PUBLISHED_PORT:-80}:80
          - ${TRAEFIK_HTTPS_PUBLISHED_PORT:-443}:443
          - ${TRAEFIK_DASHBOARD_PUBLISHED_PORT:-8080}:8080
        volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock:ro
          # - ${VOLUME_PATH:?err}/traefik/certificates:/certificates
          # - ${VOLUME_PATH:?err}/traefik/config/certificates.yaml:/config/certificates.yaml
          - ${VOLUME_PATH:?err}/traefik/letsencrypt:/letsencrypt

    powerdns:
        deploy:
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.rule=Host(`api.${DOMAIN:?err}`)"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.service=${PROJECT_NAME:-powerdns}-additional"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.entrypoints=https"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.tls=true"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.tls.certResolver=letsencrypt"
              - "traefik.http.services.${PROJECT_NAME:-powerdns}-additional.loadbalancer.server.port=8081"

        labels:
          - "traefik.enable=true"

          - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.rule=Host(`api.${DOMAIN:?err}`)"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.service=${PROJECT_NAME:-powerdns}-additional"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.entrypoints=https"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.tls=true"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns}-additional.tls.certResolver=letsencrypt"
          - "traefik.http.services.${PROJECT_NAME:-powerdns}-additional.loadbalancer.server.port=8081"

    powerdns-admin:
        deploy:
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.rule=Host(`admin.${DOMAIN:?err}`)"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.service=${PROJECT_NAME:-powerdns-admin}"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.entrypoints=https"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.tls=true"
              - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.tls.certResolver=letsencrypt"
              - "traefik.http.services.${PROJECT_NAME:-powerdns-admin}.loadbalancer.server.port=80"

        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.rule=Host(`admin.${DOMAIN:?err}`)"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.service=${PROJECT_NAME:-powerdns-admin}"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.entrypoints=https"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.tls=true"
          - "traefik.http.routers.${PROJECT_NAME:-powerdns-admin}.tls.certResolver=letsencrypt"
          - "traefik.http.services.${PROJECT_NAME:-powerdns-admin}.loadbalancer.server.port=80"

